Artificial  intelligence and Machine learning workshop
Worksheet - 0

# 4. To-Do-Exercise
**4.1 Exercise on Function**

In [ ]:
def unit_converter():
    """Converts between different units of measurement based on user choice."""
    print("Welcome to the Unit Converter!")
    print("Please choose a conversion type:")
    conversions = {
        "1": ("Meters to Feet", lambda x: x * 3.28084),
        "2": ("Feet to Meters", lambda x: x / 3.28084),
        "3": ("Kilograms to Pounds", lambda x: x * 2.20462),
        "4": ("Pounds to Kilograms", lambda x: x / 2.20462),
        "5": ("Liters to Gallons", lambda x: x * 0.264172),
        "6": ("Gallons to Liters", lambda x: x / 0.264172),
    }
    while True:
        # Display conversion options
        print("\nChoose a conversion type:")
        for key, (desc, _) in conversions.items():
            print(f"{key}. {desc}")
        choice = input("Enter 1, 2, 3, 4, 5, or 6: ").strip()
        if choice not in conversions:
            print("Invalid choice. Please try again.")
            continue  # Restart the loop
        try:
            value = float(input("Enter the value to convert: ").strip())
            print(f"Converted Value: {conversions[choice][1](value):.4f}")  # Format output to 4 decimals
        except ValueError:
            print("Invalid input. Please enter a numeric value.")
            continue  # Restart the loop
        # Ask the user if they want to perform another conversion
        restart = input("Would you like to perform another operation? (yes/no): ").strip().lower()
        if restart != "yes":
            print("Exiting the unit converter. Goodbye!")
            break

In [ ]:
unit_converter()

Welcome to the Unit Converter!
Please choose a conversion type:

Choose a conversion type:
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Enter 1, 2, 3, 4, 5, or 6: 6
Enter the value to convert: 11
Converted Value: 41.6395
Would you like to perform another operation? (yes/no): No
Exiting the unit converter. Goodbye!


# Task 2

In [ ]:
def list_operations():
    """Performs basic math operations (sum, average, max, min) on a list of numbers."""
    print("Choose an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")
    choice = input("Enter 1, 2, 3, or 4: ")
    if choice not in ["1", "2", "3", "4"]:
        print("Invalid choice.")
        return
    try:
        numbers = list(map(float, input("Enter numbers separated by space: ").split()))
        if not numbers:
            print("Error: List is empty.")
            return
        if choice == "1":
            print("Sum:", sum(numbers))
        elif choice == "2":
            print("Average:", sum(numbers) / len(numbers))
        elif choice == "3":
            print("Maximum:", max(numbers))
        elif choice == "4":
            print("Minimum:", min(numbers))
    except ValueError:
        print("Invalid input. Please enter numeric values.")

In [ ]:
list_operations()

Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter 1, 2, 3, or 4: 3
Enter numbers separated by space: 6 6 6 8
Maximum: 8.0


4.2 Exercise on List Manipulation:


1. Extract Every Other Element:


In [ ]:
def extract_every_other(lst):
    """
    Extracts every other element from a list, starting from the first element.
    Parameters:
        lst (list): The input list.
    Returns:
        list: A new list containing every other element from the original list.
    """
    return lst[::2]
New_list = [1, 3, 5, 7, 8, 9]
Extract_list = extract_every_other(New_list)
print(Extract_list)

[1, 5, 8]


2. Slice a Sublist:

In [ ]:
def get_sublist(lst, start, end):
    """
    Returns a sublist from a given list, starting from a specified index and ending at another specified index.
    Parameters:
        lst (list): The input list.
        start (int): The starting index (inclusive).
        end (int): The ending index (inclusive).
    Returns:
        list: A new list containing elements from the specified range.
    """
    return lst[start:end+1]  # +1 to include the end index
list = [11, 22, 33, 43, 54, 67]
result = get_sublist(list, 2, 4)
print(result)

[33, 43, 54]


3. Reverse a List Using Slicing:

In [ ]:
def reverse_list(lst):
    """
    Reverses a list using slicing.
    Parameters:
        lst (list): The input list.
    Returns:
        list: A new list with elements in reverse order.
    """
    return lst[::-1]  # Slicing with step -1 reverses the list
# Example usage
list = [12, 23, 34, 45, 56]
result = reverse_list(list)
print(result)

[56, 45, 34, 23, 12]


4. Remove the First and Last Elements:




In [ ]:
def remove_first_last(lst):
    """
    Removes the first and last elements of a list and returns the resulting sublist.
    Parameters:
        lst (list): The input list.
    Returns:
        list: A new list without the first and last elements.
    """
    return lst[1:-1]
list = [12, 24, 36, 47, 59]
result = remove_first_last(list)
print(result)

[24, 36, 47]


5. Get the First n Elements:

In [ ]:
def get_first_n(lst, n):
    """
    Extracts the first n elements from a list.
    Parameters:
        lst (list): The input list.
        n (int): The number of elements to extract.
    Returns:
        list: A new list containing the first n elements.
    """
    return lst[:n]
list = [11, 22, 33, 44, 55]
n = 3
result = get_first_n(list, n)
print(result)

[11, 22, 33]


6. Extract Elements from the End:

In [ ]:
def get_last_n(lst, n):
    """
    Extracts the last n elements from a list.
    Parameters:
        lst (list): The input list.
        n (int): The number of elements to extract from the end.
    Returns:
        list: A new list containing the last n elements.
    """
    return lst[-n:]
list = [14, 25, 33, 44, 55]
n = 2
result = get_last_n(list, n)
print(result)

[44, 55]


7. Extract Elements in Reverse Order:


In [ ]:
def reverse_skip(lst):
    """
    Extracts elements in reverse order, starting from the second-to-last element
    and skipping one element in between.
    Parameters:
        lst (list): The input list.
    Returns:
        list: A new list containing every second element in reverse order.
    """
    return lst[-2::-2]
list = [13, 25, 36, 45, 55, 66]
result = reverse_skip(list)
print(result)

[55, 36, 13]


# 4.3 Exercise on Nested List:

1. Flatten a Nested List:

In [ ]:
def flatten(lst):
    """
    Flattens a nested list into a single list without using recursion.
    Parameters:
        lst (list): The nested list to flatten.
    Returns:
        list: A new list containing all elements from the nested list in a single dimension.
    """
    flat_list = sum(lst, [])
    return flat_list
list = [[1, 2], [3, 4], [5]]
result = flatten(list)
print(result)

[1, 2, 3, 4, 5]


2. Accessing Nested List Elements:


In [ ]:
def access_nested_element(lst, indices):
    """
    Extracts a specific element from a nested list given its indices.
    Parameters:
        lst (list): The nested list.
        indices (list): A list of indices representing the path to the desired element.
    Returns:
        any: The element at the specified indices.
    """
    element = lst
    for index in indices:
        element = element[index]
    return element
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [2, 2]
result = access_nested_element(nested_list, indices)
print(result)

9


3. Sum of All Elements in a Nested List:

In [ ]:
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)  # Recursively sum nested lists
        else:
            total += item
nested_list = [[1, 2], [3, [4, 5]], 6]
print(sum_nested(nested_list))

21


4. Remove Specific Element from a Nested List:


In [ ]:
def remove_element(lst, elem):
    result = []
    for item in lst:
        if isinstance(item, list):
            filtered_sublist = remove_element(item, elem)  # Recursively filter nested lists
            if filtered_sublist:  # Only append non-empty lists
                result.append(filtered_sublist)
        elif item != elem:
            result.append(item)  # Append only non-matching elements
    return result
nested_list = [[1, 2], [3, 2], [4, 5]]
element_to_remove = 2
print(remove_element(nested_list, element_to_remove))

[[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:


In [ ]:
def find_max(lst):
    max_val = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_val = max(max_val, find_max(item))  # Recursively find max in nested lists
        else:
            max_val = max(max_val, item)  # Update max if item is greater
    return max_val
nested_list = [[1, 2], [3, [44, 5]], 7]
print(find_max(nested_list))

44


6. Count Occurrences of an Element in a Nested List:

In [ ]:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)  # Recursively count occurrences in nested lists
        elif item == elem:
            count += 1  # Increment count if item matches elem
    return count
nested_list = [[1, 2], [2, 3], [2, 4]]
element_to_count = 3
print(count_occurrences(nested_list, element_to_count))

1


7. Flatten a List of Lists of Lists:


In [ ]:
def deep_flatten(lst):
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))  # Recursively flatten nested lists
        else:
            flat_list.append(item)
    return flat_list
nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print(deep_flatten(nested_list))

[1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:


In [ ]:
def sum_and_count(lst):
    total = 0
    count = 0
    for item in lst:
        if isinstance(item, list):
            sub_total, sub_count = sum_and_count(item)  # Recursively sum and count elements
            total += sub_total
            count += sub_count
        else:
            total += item
            count += 1
    return total, count
def average_nested(lst):
    total, count = sum_and_count(lst)
    return total / count if count > 0 else 0
nested_list = [[1, 22], [3, 4], [5, 6]]
print(average_nested(nested_list))

6.833333333333333


# 10 To - Do - **NumPy**

10.1 Basic Vector and Matrix Operation with Numpy.

Problem - 1: Array Creation:

In [ ]:
import numpy as np
# 1. set an empty array with size 2x2
empty_array = np.empty((2,2))
# 2.set an all-one array with size 4x2
ones_array = np.ones((4,2))
# 3. Return a new array of given shape and type, filled with a given value
filled_array = np.full((3,3), 7)
# 4. Return a new array of zeros with the same shape and type as a given array
reference_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(reference_array)
# 5. Return a new array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(reference_array)
# 6. Convert an existing list to a numpy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("1. Empty Array (2x2):\n", empty_array, "\n")
print("2. All Ones Array (4x2):\n", ones_array, "\n")
print("3. Filled Array (3x3) with 7:\n", filled_array, "\n")
print("4. Zeros Like Reference Array:\n", zeros_like_array, "\n")
print("5. Ones Like Reference Array:\n", ones_like_array, "\n")
print("6. Converted List to Numpy Array:\n", numpy_array, "\n")

1. Empty Array (2x2):
 [[2.74412928e-316 0.00000000e+000]
 [1.68891191e-052 9.72679674e-067]] 

2. All Ones Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 

3. Filled Array (3x3) with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]] 

4. Zeros Like Reference Array:
 [[0 0]
 [0 0]] 

5. Ones Like Reference Array:
 [[1 1]
 [1 1]] 

6. Converted List to Numpy Array:
 [1 2 3 4] 



Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:


In [ ]:
# 1. Create an array with values ranging from 10 to 49
array_range = np.arange(10, 50)
print("1. Array with values from 10 to 49:\n", array_range, "\n")
# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("2. 3x3 Matrix with values from 0 to 8:\n", matrix_3x3, "\n")
# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("3. 3x3 Identity Matrix:\n", identity_matrix, "\n")
# 4. Create a random array of size 30 and find the mean of the array
random_array_30 = np.random.random(30)
mean_value = random_array_30.mean()
print("4. Mean of a random array of size 30:", mean_value, "\n")
# 5. Create a 10x10 array with random values and find the min and max values
random_matrix_10x10 = np.random.random((10, 10))
min_value = random_matrix_10x10.min()
max_value = random_matrix_10x10.max()
print("5. 10x10 Random Matrix Min Value:", min_value)
print("   10x10 Random Matrix Max Value:", max_value, "\n")
# 6. Create a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("6. Zero Array with 5th element as 1:\n", zero_array, "\n")
# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1,2,0,0,4,0])
reversed_arr = arr[::-1]
print("7. Reversed Array:\n", reversed_arr, "\n")
# 8. Create a 2D array with 1 on the border and 0 inside
border_array = np.ones((5,5))
border_array[1:-1, 1:-1] = 0
print("8. 2D Array with border 1 and inside 0:\n", border_array, "\n")
# 9. Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8,8), dtype=int)
checkerboard[1::2, ::2] = 1  # Filling 1s at alternate positions
checkerboard[::2, 1::2] = 1
print("9. 8x8 Checkerboard Pattern:\n", checkerboard, "\n")


1. Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] 

2. 3x3 Matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

3. 3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

4. Mean of a random array of size 30: 0.5421834250114368 

5. 10x10 Random Matrix Min Value: 0.0011689284598189742
   10x10 Random Matrix Max Value: 0.998620497187362 

6. Zero Array with 5th element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] 

7. Reversed Array:
 [0 4 0 0 2 1] 

8. 2D Array with border 1 and inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]] 

9. 8x8 Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]] 



Problem - 3: Array Operations:

In [ ]:
# Define the given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
# 1. Add the two arrays x and y
sum_xy = x + y
print("1. Sum of x and y:\n", sum_xy, "\n")
# 2. Subtract the two arrays x and y
diff_xy = x - y
print("2. Difference of x and y:\n", diff_xy, "\n")

# 3. Multiply the array x with an integer (e.g., 3)
multiplied_x = x * 3
print("3. x multiplied by 3:\n", multiplied_x, "\n")
# 4. Find the square of each element of x
square_x = np.square(x)
print("4. Square of elements in x:\n", square_x, "\n")

# 5. Find the dot product between:
dot_vw = np.dot(v, w)  # v . w
dot_xv = np.dot(x, v)  # x . v
dot_xy = np.dot(x, y)  # x . y
print("5. Dot product v . w:", dot_vw)
print("   Dot product x . v:\n", dot_xv)
print("   Dot product x . y:\n", dot_xy, "\n")
# 6. Concatenate x and y along rows & v and w along columns
concat_xy_row = np.concatenate((x, y), axis=0)  # Row-wise concatenation
concat_vw_col = np.column_stack((v, w))  # Column-wise concatenation
print("6. Concatenation of x and y along rows:\n", concat_xy_row, "\n")
print("   Concatenation of v and w along columns:\n", concat_vw_col, "\n")
# 7. Attempt to concatenate x and v
try:
    concat_xv = np.concatenate((x, v), axis=0)  # This should raise an error
except ValueError as e:
    concat_xv = str(e)  # Capture the error message
print("7. Attempt to Concatenate x and v (Expected Error):\n", concat_xv, "\n")

1. Sum of x and y:
 [[ 6  8]
 [10 13]] 

2. Difference of x and y:
 [[-4 -4]
 [-4 -3]] 

3. x multiplied by 3:
 [[ 3  6]
 [ 9 15]] 

4. Square of elements in x:
 [[ 1  4]
 [ 9 25]] 

5. Dot product v . w: 219
   Dot product x . v:
 [29 77]
   Dot product x . y:
 [[19 22]
 [50 58]] 

6. Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]] 

   Concatenation of v and w along columns:
 [[ 9 11]
 [10 12]] 

7. Attempt to Concatenate x and v (Expected Error):
 all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s) 



Problem - 4: Matrix Operations:


In [ ]:
# Define the given matrices A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
# 1. Prove A * A⁻¹ = I
A_inv = np.linalg.inv(A)  # Compute inverse of A
identity_matrix = np.dot(A, A_inv)  # A * A⁻¹
print("1. A * A⁻¹ = Identity Matrix:\n", identity_matrix, "\n")
# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
is_AB_equal_BA = np.array_equal(AB, BA)  # Check if AB == BA
print("2. AB ≠ BA (Matrix Multiplication is not commutative):", is_AB_equal_BA, "\n")

# 3. Prove (AB)^T = B^T * A^T
AB_T = np.transpose(AB)  # (AB)^T
B_T_A_T = np.dot(np.transpose(B), np.transpose(A))  # B^T * A^T
is_transpose_property_valid = np.array_equal(AB_T, B_T_A_T)  # Check if (AB)^T == B^T * A^T
print("3. (AB)^T = B^T * A^T (Matrix Transpose Property):", is_transpose_property_valid, "\n")
# Solve the system of linear equations using inverse method
# Representing equations in matrix form: AX = B
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_eq = np.array([-1, -3, 9])
# Solve for X using inverse method
A_inv_eq = np.linalg.inv(A_eq)  # Compute inverse of A_eq
X_solution = np.dot(A_inv_eq, B_eq)  # X = A⁻¹ * B
print("4. Solution to the system of linear equations using Inverse Method:\n", X_solution)


1. A * A⁻¹ = Identity Matrix:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]] 

2. AB ≠ BA (Matrix Multiplication is not commutative): False 

3. (AB)^T = B^T * A^T (Matrix Transpose Property): True 

4. Solution to the system of linear equations using Inverse Method:
 [ 2.  1. -2.]


# 10.2 Experiment: How Fast is Numpy?

In [ ]:
import numpy as np
import time

1. Element-wise Addition:

In [ ]:
# Define size parameters
size = 1_000_000  # 1 million elements
matrix_size = 1000  # 1000x1000 matrix
# Generate random data for lists and arrays
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]
array1 = np.arange(size)
array2 = np.arange(size)
# 1. Element-wise Addition
# Using Python lists
start_time = time.time()
list_addition = [list1[i] + list2[i] for i in range(size)]
list_add_time = time.time() - start_time
# Using NumPy arrays
start_time = time.time()
array_addition = array1 + array2
array_add_time = time.time() - start_time
print(f"Element-wise Addition - Python List Time: {list_add_time:.6f} sec")
print(f"Element-wise Addition - NumPy Array Time: {array_add_time:.6f} sec\n")

Element-wise Addition - Python List Time: 0.087779 sec
Element-wise Addition - NumPy Array Time: 0.002814 sec



In [ ]:
# 2. Element-wise Multiplication
# Using Python lists
start_time = time.time()
list_multiplication = [list1[i] * list2[i] for i in range(size)]
list_mult_time = time.time() - start_time
# Using NumPy arrays
start_time = time.time()
array_multiplication = array1 * array2
array_mult_time = time.time() - start_time
print(f"Element-wise Multiplication - Python List Time: {list_mult_time:.6f} sec")
print(f"Element-wise Multiplication - NumPy Array Time: {array_mult_time:.6f} sec\n")

Element-wise Multiplication - Python List Time: 0.073600 sec
Element-wise Multiplication - NumPy Array Time: 0.004713 sec



In [ ]:
#3.Dot Product
# Using Python lists
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
list_dot_time = time.time() - start_time
# Using NumPy arrays
start_time = time.time()
dot_product_array = np.dot(array1, array2)
array_dot_time = time.time() - start_time
print(f"Dot Product - Python List Time: {list_dot_time:.6f} sec")
print(f"Dot Product - NumPy Array Time: {array_dot_time:.6f} sec\n")

Dot Product - Python List Time: 0.111098 sec
Dot Product - NumPy Array Time: 0.001304 sec



In [ ]:
# 4. Matrix Multiplication (Skipping Python Lists Due to Slow Execution)
# Generate random 1000x1000 matrices for NumPy
array_matrix1 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)
array_matrix2 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)
# Using NumPy arrays
start_time = time.time()
array_matrix_result = np.dot(array_matrix1, array_matrix2)
array_matrix_time = time.time() - start_time
print(f"Matrix Multiplication (1000x1000) - NumPy Array Time: {array_matrix_time:.6f} sec")
print("Matrix Multiplication using Python Lists skipped due to slow execution.")

Matrix Multiplication (1000x1000) - NumPy Array Time: 0.963412 sec
Matrix Multiplication using Python Lists skipped due to slow execution.


here we say that by the evaluating of the output.
Numpy is more fater rather than python list in all operations.
Matrix multiplication using Numpy is fater while python list are too much time taken for give the output.